pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://maven.fabricmc.net/" }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
    }
}

rootProject.name = "mcgf-ai-companion"
